### ISSUE TITLE
Release 0.2.0 checklist

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/tricolour#93]
Starting to work on this. Multiple things come to mind:
- [x] drop python3.6 support
- [x] add python3.10 support and testing
- [ ] #81 add flagbackup support
- [x] logging filename changes requested in #92 
- [ ] switch over to dask-ms zarr format
- [x] ditch setuptools for something newer and fully pep517 compliant e.g. poetry
- [x] ~~Move to a newer version of numpy~~. This should happen with the latest dask-ms version by default

**Comment by bennahugo** [comment]
dtypes have been updated to support going to a higher version of numpy
